database:
  database_name: 'ledger_development'
  host: 'db'
  port: 3306
  username: 'root'
  password: 'root'
domain_name: "http://localhost:7004"
api_link: "http://localhost:7004/services/api/v1/links"
documentation_link: "http://documentation-link"
host_url: "http://localhost:7004"
redis_cache:
  redis_uri: "redis://redis:6379/3"
locker:
  redis_uri: "redis://redis:6379/4"
sidekiq:
  redis_uri: "redis://redis:6379/5"
  basic_auth:
    username: 'sidekiq'
    password: '1234'
nextgen:
  base_url: 'http://95.177.221.161:13001'
  secret_key: '123'
  enabled: false
client_app_requests_origin: 'localhost:4204'
disable_permission_check:
  all: false
frontend:
  check_login: 'http://localhost:4204/check_login'
  home_url: 'http://localhost:4204'
mailer:
  host: "mailcatcher"
  port: "1025"
  domain: "http://localhost:7071"
  authentication: "plain"
  user_name: ""
  password: ""
  from_email: "admin@.com"
  exception_alert:
    - mumair@.com
    - tshoaib@.com
